///////////////////////////////////////////////////////////
//  IDataProxy.as
//  Macromedia ActionScript Implementation of the Interface IDataProxy
//  Generated by Enterprise Architect
//  Created on:      11-八月-2010 14:51:59
//  Original author: Pengx
///////////////////////////////////////////////////////////

package cactus.ui.data
{
	import flash.events.IEventDispatcher;

	/**
	 * 数据代理接口
	 * 负责提供给显示对象数据
	 * 用于实现数据中间层，切换模拟数据和真实数据、
	 * 需抛出DataEvent的所以事件
	 * @author Pengx
	 * @version 1.0
	 * @created 11-八月-2010 14:51:59
	 */
	public interface IDataProxy extends IEventDispatcher
	{
		/**
		 * 准备（在需要使用数据前，都需要准备数据）
		 * 准备完毕会抛出DataEvent.DATASOURCE_READY
		 */
		function prepareReady(): void;
	}//end IDataProxy

}