///////////////////////////////////////////////////////////
//  BaseTestDataProxy.as
//  Macromedia ActionScript Implementation of the Class BaseTestDataProxy
//  Generated by Enterprise Architect
//  Created on:      11-八月-2010 14:51:59
//  Original author: Pengx
///////////////////////////////////////////////////////////

package cactus.ui.data.local
{
	import cactus.ui.data.IDataProxy;
	import cactus.ui.events.DataEvent;
	
	import flash.events.EventDispatcher;

	/**
	 * 测试数据代理基类
	 * @author Pengx
	 * @version 1.0
	 * @created 11-八月-2010 14:51:59
	 */
	public class BaseTestDataProxy extends EventDispatcher implements IDataProxy
	{
		public function BaseTestDataProxy(){

		}
		
		public function prepareReady(): void
		{
			//测试数据不用准备，hoho
			this.dispatchEvent(new DataEvent(DataEvent.DATA_READY));
		}

	}//end BaseTestDataProxy

}